name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  snap_package:
    
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - name: Install snap tools
      run: |
        sudo apt update || true
        sudo apt install -y snapd
        snap version

        sudo snap install --classic --channel=7.x/stable snapcraft
        
        # workaround for GithubActionsCI+snapcraft, see https://forum.snapcraft.io/t/permissions-problem-using-snapcraft-in-azure-pipelines/13258/14?u=knocte
        sudo chown root:root /
        
        snapcraft --version

    - name: Generate snap package
      run: |
        sudo snap install --channel=latest/stable gnome-42-2204-sdk
        sudo snap install --channel=latest/stable gnome-42-2204
        sudo snap install --channel=latest/stable gtk-common-themes
        snapcraft --destructive-mode || cat /home/runner/.local/state/snapcraft/log/*.log

    - name: Install snap
      # dangerous because it's a local snap (not one from the SnapStore)
      run: sudo snap install --dangerous *.snap
    
    - uses: actions/upload-artifact@v3
      name: Upload snap package as artifact
      with:
        name: snap
        path: ./*.snap
